# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 576)
        self.mainLayout = QtWidgets.QWidget(MainWindow)
        self.mainLayout.setObjectName("mainLayout")
        self.checkButton = QtWidgets.QPushButton(self.mainLayout)
        self.checkButton.setGeometry(QtCore.QRect(30, 490, 93, 28))
        self.checkButton.setObjectName("checkButton")
        self.clearButton = QtWidgets.QPushButton(self.mainLayout)
        self.clearButton.setGeometry(QtCore.QRect(30, 520, 93, 28))
        self.clearButton.setObjectName("clearButton")
        self.answerLabel = QtWidgets.QLabel(self.mainLayout)
        self.answerLabel.setGeometry(QtCore.QRect(230, 490, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(24)
        self.answerLabel.setFont(font)
        self.answerLabel.setObjectName("answerLabel")
        MainWindow.setCentralWidget(self.mainLayout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkButton.setText(_translate("MainWindow", "Check"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.answerLabel.setText(_translate("MainWindow", "I think it\'s:"))
